import random

US_STATES = [
    "Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida",
    "Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine",
    "Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska",
    "Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota",
    "Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee",
    "Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"
]
# ------------------ Position-specific stat ranges ------------------
STAT_RANGES = {
    "PG": {
        "bad": {
            "close_shot": (35, 75),
            "driving_layup": (40, 75),
            "driving_dunk": (25, 75),
            "standing_dunk": (20, 55),
            "post_moves": (30, 55),
            "mid_range_shot": (30, 80),
            "three_point_shot": (30, 80),
            "free_throw": (40, 95),
            "pass_accuracy": (50, 75),
            "ball_handle": (50, 75),
            "speed_with_ball": (65, 85),
            "interior_defense": (20, 50),
            "perimeter_defense": (35, 80),
            "steal": (30, 80),
            "block": (20, 50),
            "offensive_rebounding": (20, 50),
            "defensive_rebounding": (30, 65),
            "speed": (60, 90),
            "strength": (15, 45),
            "vertical": (20, 75),
            "potential": (45, 85),
        },
        "recruit": {  # exactly what you gave
            "close_shot": (35, 95),
            "driving_layup": (45, 95),
            "driving_dunk": (35, 95),
            "standing_dunk": (30, 60),
            "post_moves": (30, 60),
            "mid_range_shot": (40, 95),
            "three_point_shot": (40, 99),
            "free_throw": (55, 99),
            "pass_accuracy": (50, 99),
            "ball_handle": (50, 99),
            "speed_with_ball": (75, 99),
            "interior_defense": (35, 60),
            "perimeter_defense": (35, 95),
            "steal": (40, 95),
            "block": (30, 65),
            "offensive_rebounding": (30, 65),
            "defensive_rebounding": (40, 85),
            "speed": (75, 99),
            "strength": (20, 75),
            "vertical": (30, 95),
            "potential": (60, 99),
        },
        "mid": {
            "close_shot": (55, 97),
            "driving_layup": (60, 97),
            "driving_dunk": (45, 97),
            "standing_dunk": (35, 65),
            "post_moves": (45, 65),
            "mid_range_shot": (55, 97),
            "three_point_shot": (55, 99),
            "free_throw": (65, 99),
            "pass_accuracy": (65, 99),
            "ball_handle": (65, 99),
            "speed_with_ball": (80, 99),
            "interior_defense": (40, 65),
            "perimeter_defense": (55, 97),
            "steal": (55, 97),
            "block": (35, 70),
            "offensive_rebounding": (35, 70),
            "defensive_rebounding": (45, 90),
            "speed": (80, 99),
            "strength": (25, 80),
            "vertical": (40, 97),
            "potential": (65, 99),
        },
        "good": {
            "close_shot": (60, 98),
            "driving_layup": (70, 98),
            "driving_dunk": (55, 98),
            "standing_dunk": (40, 70),
            "post_moves": (50, 70),
            "mid_range_shot": (65, 98),
            "three_point_shot": (65, 99),
            "free_throw": (65, 99),
            "pass_accuracy": (75, 99),
            "ball_handle": (75, 99),
            "speed_with_ball": (85, 99),
            "interior_defense": (45, 70),
            "perimeter_defense": (60, 98),
            "steal": (55, 98),
            "block": (40, 75),
            "offensive_rebounding": (40, 75),
            "defensive_rebounding": (50, 92),
            "speed": (80, 99),
            "strength": (30, 85),
            "vertical": (50, 98),
            "potential": (75, 99),
        },
        "elite": {
            "close_shot": (80, 99),
            "driving_layup": (80, 99),
            "driving_dunk": (70, 99),
            "standing_dunk": (45, 75),
            "post_moves": (60, 75),
            "mid_range_shot": (75, 99),
            "three_point_shot": (75, 99),
            "free_throw": (80, 99),
            "pass_accuracy": (80, 99),
            "ball_handle": (80, 99),
            "speed_with_ball": (90, 99),
            "interior_defense": (50, 75),
            "perimeter_defense": (70, 99),
            "steal": (70, 99),
            "block": (45, 80),
            "offensive_rebounding": (45, 80),
            "defensive_rebounding": (55, 95),
            "speed": (90, 99),
            "strength": (40, 90),
            "vertical": (60, 99),
            "potential": (85, 99),
        },
    },
    "SG": {
        "bad": {
            "close_shot": (35, 70),
            "driving_layup": (40, 70),
            "driving_dunk": (25, 70),
            "standing_dunk": (20, 55),
            "post_moves": (35, 55),
            "mid_range_shot": (40, 80),
            "three_point_shot": (40, 85),
            "free_throw": (40, 75),
            "pass_accuracy": (40, 75),
            "ball_handle": (45, 80),
            "speed_with_ball": (65, 75),
            "interior_defense": (25, 55),
            "perimeter_defense": (45, 70),
            "steal": (35, 70),
            "block": (35, 55),
            "offensive_rebounding": (25, 55),
            "defensive_rebounding": (35, 65),
            "speed": (70, 85),
            "strength": (20, 50),
            "vertical": (45, 70),
            "potential": (45, 85),
        },
        "recruit": {
            "close_shot": (45, 99),
            "driving_layup": (45, 95),
            "driving_dunk": (45, 95),
            "standing_dunk": (30, 65),
            "post_moves": (30, 65),
            "mid_range_shot": (40, 95),
            "three_point_shot": (40, 99),
            "free_throw": (55, 99),
            "pass_accuracy": (45, 95),
            "ball_handle": (50, 95),
            "speed_with_ball": (65, 95),
            "interior_defense": (35, 65),
            "perimeter_defense": (35, 95),
            "steal": (35, 95),
            "block": (30, 65),
            "offensive_rebounding": (30, 65),
            "defensive_rebounding": (40, 85),
            "speed": (70, 95),
            "strength": (25, 75),
            "vertical": (35, 95),
            "potential": (60, 99),
        },
        "mid": {
            "close_shot": (60, 97),
            "driving_layup": (60, 97),
            "driving_dunk": (60, 97),
            "standing_dunk": (35, 70),
            "post_moves": (55, 70),
            "mid_range_shot": (60, 97),
            "three_point_shot": (60, 99),
            "free_throw": (65, 99),
            "pass_accuracy": (60, 97),
            "ball_handle": (65, 97),
            "speed_with_ball": (75, 97),
            "interior_defense": (40, 70),
            "perimeter_defense": (55, 97),
            "steal": (50, 97),
            "block": (35, 70),
            "offensive_rebounding": (35, 70),
            "defensive_rebounding": (45, 90),
            "speed": (75, 97),
            "strength": (30, 80),
            "vertical": (60, 97),
            "potential": (75, 99),
        },
        "good": {
            "close_shot": (70, 98),
            "driving_layup": (75, 98),
            "driving_dunk": (65, 98),
            "standing_dunk": (40, 75),
            "post_moves": (60, 85),
            "mid_range_shot": (70, 98),
            "three_point_shot": (70, 99),
            "free_throw": (70, 99),
            "pass_accuracy": (65, 98),
            "ball_handle": (75, 98),
            "speed_with_ball": (80, 98),
            "interior_defense": (45, 75),
            "perimeter_defense": (60, 98),
            "steal": (60, 98),
            "block": (40, 75),
            "offensive_rebounding": (45, 75),
            "defensive_rebounding": (55, 92),
            "speed": (80, 98),
            "strength": (35, 85),
            "vertical": (65, 98),
            "potential": (75, 99),
        },
        "elite": {
            "close_shot": (80, 99),
            "driving_layup": (80, 99),
            "driving_dunk": (80, 99),
            "standing_dunk": (45, 80),
            "post_moves": (65, 90),
            "mid_range_shot": (80, 99),
            "three_point_shot": (80, 99),
            "free_throw": (80, 99),
            "pass_accuracy": (75, 99),
            "ball_handle": (80, 99),
            "speed_with_ball": (80, 99),
            "interior_defense": (50, 80),
            "perimeter_defense": (70, 99),
            "steal": (70, 99),
            "block": (45, 80),
            "offensive_rebounding": (45, 80),
            "defensive_rebounding": (55, 95),
            "speed": (80, 99),
            "strength": (40, 90),
            "vertical": (65, 99),
            "potential": (85, 99),
        },
    },
    "SF": {
        "bad": {
            "close_shot": (35, 75),
            "driving_layup": (35, 75),
            "driving_dunk": (35, 75),
            "standing_dunk": (30, 70),
            "post_moves": (30, 70),
            "mid_range_shot": (35, 80),
            "three_point_shot": (35, 80),
            "free_throw": (45, 90),
            "pass_accuracy": (35, 70),
            "ball_handle": (35, 70),
            "speed_with_ball": (55, 75),
            "interior_defense": (35, 70),
            "perimeter_defense": (35, 75),
            "steal": (35, 70),
            "block": (35, 70),
            "offensive_rebounding": (35, 70),
            "defensive_rebounding": (35, 70),
            "speed": (60, 85),
            "strength": (35, 65),
            "vertical": (35, 70),
            "potential": (45, 85),
        },
        "recruit": {
            "close_shot": (55, 99),
            "driving_layup": (50, 95),
            "driving_dunk": (50, 95),
            "standing_dunk": (40, 85),
            "post_moves": (40, 85),
            "mid_range_shot": (45, 95),
            "three_point_shot": (45, 95),
            "free_throw": (55, 95),
            "pass_accuracy": (45, 95),
            "ball_handle": (45, 95),
            "speed_with_ball": (65, 95),
            "interior_defense": (40, 85),
            "perimeter_defense": (40, 95),
            "steal": (40, 95),
            "block": (40, 85),
            "offensive_rebounding": (40, 85),
            "defensive_rebounding": (45, 95),
            "speed": (65, 95),
            "strength": (35, 85),
            "vertical": (45, 95),
            "potential": (60, 99),
        },
        "mid": {
            "close_shot": (70, 97),
            "driving_layup": (65, 97),
            "driving_dunk": (65, 97),
            "standing_dunk": (45, 87),
            "post_moves": (45, 87),
            "mid_range_shot": (60, 97),
            "three_point_shot": (60, 97),
            "free_throw": (65, 97),
            "pass_accuracy": (60, 97),
            "ball_handle": (60, 97),
            "speed_with_ball": (70, 97),
            "interior_defense": (55, 87),
            "perimeter_defense": (55, 97),
            "steal": (55, 97),
            "block": (55, 87),
            "offensive_rebounding": (55, 87),
            "defensive_rebounding": (55, 97),
            "speed": (70, 97),
            "strength": (45, 87),
            "vertical": (60, 97),
            "potential": (75, 99),
        },
        "good": {
            "close_shot": (75, 98),
            "driving_layup": (75, 98),
            "driving_dunk": (75, 98),
            "standing_dunk": (55, 90),
            "post_moves": (55, 90),
            "mid_range_shot": (70, 98),
            "three_point_shot": (70, 98),
            "free_throw": (70, 98),
            "pass_accuracy": (65, 98),
            "ball_handle": (65, 98),
            "speed_with_ball": (75, 98),
            "interior_defense": (60, 90),
            "perimeter_defense": (60, 98),
            "steal": (60, 98),
            "block": (60, 90),
            "offensive_rebounding": (55, 90),
            "defensive_rebounding": (55, 98),
            "speed": (75, 98),
            "strength": (45, 90),
            "vertical": (65, 98),
            "potential": (80, 99),
        },
        "elite": {
            "close_shot": (85, 99),
            "driving_layup": (80, 99),
            "driving_dunk": (80, 99),
            "standing_dunk": (60, 95),
            "post_moves": (60, 95),
            "mid_range_shot": (75, 99),
            "three_point_shot": (75, 99),
            "free_throw": (70, 99),
            "pass_accuracy": (75, 99),
            "ball_handle": (75, 99),
            "speed_with_ball": (80, 99),
            "interior_defense": (65, 95),
            "perimeter_defense": (70, 99),
            "steal": (70, 99),
            "block": (70, 95),
            "offensive_rebounding": (60, 95),
            "defensive_rebounding": (65, 99),
            "speed": (80, 99),
            "strength": (55, 95),
            "vertical": (75, 99),
            "potential": (95, 99),
        },
    },
    "PF": {
        "bad": {
            "close_shot": (45, 80),
            "driving_layup": (40, 75),
            "driving_dunk": (40, 75),
            "standing_dunk": (45, 80),
            "post_moves": (40, 75),
            "mid_range_shot": (40, 75),
            "three_point_shot": (40, 75),
            "free_throw": (40, 85),
            "pass_accuracy": (35, 70),
            "ball_handle": (35, 60),
            "speed_with_ball": (35, 55),
            "interior_defense": (40, 75),
            "perimeter_defense": (35, 60),
            "steal": (35, 60),
            "block": (35, 75),
            "offensive_rebounding": (40, 75),
            "defensive_rebounding": (40, 75),
            "speed": (35, 60),
            "strength": (40, 75),
            "vertical": (40, 65),
            "potential": (45, 75),
        },
        "recruit": {
            "close_shot": (50, 95),
            "driving_layup": (40, 85),
            "driving_dunk": (35, 99),
            "standing_dunk": (55, 99),
            "post_moves": (45, 95),
            "mid_range_shot": (40, 90),
            "three_point_shot": (35, 90),
            "free_throw": (45, 85),
            "pass_accuracy": (40, 80),
            "ball_handle": (40, 75),
            "speed_with_ball": (40, 70),
            "interior_defense": (45, 95),
            "perimeter_defense": (35, 75),
            "steal": (35, 80),
            "block": (45, 99),
            "offensive_rebounding": (45, 95),
            "defensive_rebounding": (45, 95),
            "speed": (45, 75),
            "strength": (45, 95),
            "vertical": (30, 85),
            "potential": (60, 99),
        },
        "mid": {
            "close_shot": (65, 97),
            "driving_layup": (55, 87),
            "driving_dunk": (55, 97),
            "standing_dunk": (60, 97),
            "post_moves": (60, 97),
            "mid_range_shot": (55, 92),
            "three_point_shot": (55, 92),
            "free_throw": (55, 87),
            "pass_accuracy": (55, 85),
            "ball_handle": (45, 80),
            "speed_with_ball": (45, 75),
            "interior_defense": (55, 97),
            "perimeter_defense": (40, 77),
            "steal": (50, 85),
            "block": (55, 97),
            "offensive_rebounding": (55, 97),
            "defensive_rebounding": (55, 97),
            "speed": (50, 77),
            "strength": (55, 97),
            "vertical": (40, 87),
            "potential": (70, 99),
        },
        "good": {
            "close_shot": (75, 98),
            "driving_layup": (65, 90),
            "driving_dunk": (65, 98),
            "standing_dunk": (65, 98),
            "post_moves": (65, 98),
            "mid_range_shot": (55, 94),
            "three_point_shot": (55, 94),
            "free_throw": (60, 90),
            "pass_accuracy": (55, 90),
            "ball_handle": (50, 85),
            "speed_with_ball": (50, 80),
            "interior_defense": (65, 98),
            "perimeter_defense": (45, 80),
            "steal": (45, 87),
            "block": (65, 98),
            "offensive_rebounding": (65, 98),
            "defensive_rebounding": (65, 98),
            "speed": (55, 80),
            "strength": (65, 98),
            "vertical": (50, 90),
            "potential": (80, 99),
        },
        "elite": {
            "close_shot": (80, 99),
            "driving_layup": (75, 95),
            "driving_dunk": (75, 99),
            "standing_dunk": (75, 99),
            "post_moves": (75, 99),
            "mid_range_shot": (65, 99),
            "three_point_shot": (60, 99),
            "free_throw": (70, 95),
            "pass_accuracy": (65, 95),
            "ball_handle": (60, 90),
            "speed_with_ball": (55, 85),
            "interior_defense": (75, 99),
            "perimeter_defense": (55, 85),
            "steal": (50, 90),
            "block": (75, 99),
            "offensive_rebounding": (75, 99),
            "defensive_rebounding": (75, 99),
            "speed": (60, 85),
            "strength": (75, 99),
            "vertical": (60, 95),
            "potential": (85, 99),
        },
    },
    "C": {
        "bad": {
            "close_shot": (45, 80),
            "driving_layup": (35, 60),
            "driving_dunk": (35, 75),
            "standing_dunk": (50, 85),
            "post_moves": (45, 75),
            "mid_range_shot": (30, 65),
            "three_point_shot": (30, 65),
            "free_throw": (30, 85),
            "pass_accuracy": (25, 60),
            "ball_handle": (25, 50),
            "speed_with_ball": (25, 50),
            "interior_defense": (50, 80),
            "perimeter_defense": (25, 50),
            "steal": (25, 55),
            "block": (40, 80),
            "offensive_rebounding": (50, 80),
            "defensive_rebounding": (50, 80),
            "speed": (25, 55),
            "strength": (45, 80),
            "vertical": (25, 60),
            "potential": (45, 75),
        },
        "recruit": {
            "close_shot": (50, 99),
            "driving_layup": (40, 75),
            "driving_dunk": (40, 99),
            "standing_dunk": (55, 99),
            "post_moves": (50, 99),
            "mid_range_shot": (35, 85),
            "three_point_shot": (30, 90),
            "free_throw": (40, 90),
            "pass_accuracy": (35, 85),
            "ball_handle": (30, 60),
            "speed_with_ball": (30, 60),
            "interior_defense": (55, 99),
            "perimeter_defense": (35, 65),
            "steal": (40, 75),
            "block": (45, 99),
            "offensive_rebounding": (55, 99),
            "defensive_rebounding": (55, 99),
            "speed": (30, 70),
            "strength": (55, 99),
            "vertical": (35, 85),
            "potential": (60, 99),
        },
        "mid": {
            "close_shot": (70, 99),
            "driving_layup": (55, 80),
            "driving_dunk": (55, 99),
            "standing_dunk": (70, 99),
            "post_moves": (65, 99),
            "mid_range_shot": (50, 87),
            "three_point_shot": (35, 92),
            "free_throw": (50, 92),
            "pass_accuracy": (45, 90),
            "ball_handle": (35, 65),
            "speed_with_ball": (35, 65),
            "interior_defense": (65, 99),
            "perimeter_defense": (40, 70),
            "steal": (45, 80),
            "block": (60, 99),
            "offensive_rebounding": (65, 99),
            "defensive_rebounding": (65, 99),
            "speed": (35, 75),
            "strength": (65, 99),
            "vertical": (45, 87),
            "potential": (70, 99),
        },
        "good": {
            "close_shot": (80, 99),
            "driving_layup": (65, 85),
            "driving_dunk": (70, 99),
            "standing_dunk": (75, 99),
            "post_moves": (75, 99),
            "mid_range_shot": (55, 95),
            "three_point_shot": (40, 95),
            "free_throw": (55, 93),
            "pass_accuracy": (50, 93),
            "ball_handle": (40, 70),
            "speed_with_ball": (40, 70),
            "interior_defense": (80, 99),
            "perimeter_defense": (45, 75),
            "steal": (50, 85),
            "block": (75, 99),
            "offensive_rebounding": (75, 99),
            "defensive_rebounding": (75, 99),
            "speed": (40, 80),
            "strength": (75, 99),
            "vertical": (55, 90),
            "potential": (80, 99),
        },
        "elite": {
            "close_shot": (85, 99),
            "driving_layup": (70, 90),
            "driving_dunk": (75, 99),
            "standing_dunk": (80, 99),
            "post_moves": (80, 99),
            "mid_range_shot": (60, 95),
            "three_point_shot": (50, 95),
            "free_throw": (65, 95),
            "pass_accuracy": (55, 95),
            "ball_handle": (45, 75),
            "speed_with_ball": (45, 75),
            "interior_defense": (85, 99),
            "perimeter_defense": (50, 80),
            "steal": (55, 90),
            "block": (80, 99),
            "offensive_rebounding": (85, 99),
            "defensive_rebounding": (85, 99),
            "speed": (45, 85),
            "strength": (85, 99),
            "vertical": (65, 95),
            "potential": (85, 99),
        },
    },
}

# Height and weight ranges
HEIGHT_RANGES = {
    "PG": (68, 78),
    "SG": (72, 80),
    "SF": (75, 82),
    "PF": (78, 84),
    "C": (80, 88),
}

WEIGHT_RANGES = {
    "PG": (160, 210),
    "SG": (170, 220),
    "SF": (180, 230),
    "PF": (190, 250),
    "C": (200, 300),
}

FIRST_NAMES = ["John", "Mike", "Chris", "Kevin", "James", "Alex", "David", "Marcus"]
LAST_NAMES = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis"]

# ------------------ Player Generator ------------------
def generate_player(position=None, skillLvl="recruit"):
    # If position not provided, pick randomly
    if position is None:
        position = random.choice(list(STAT_RANGES.keys()))

    # Ensure skillLvl exists for the position
    if skillLvl not in STAT_RANGES[position]:
        raise ValueError(f"Skill level '{skillLvl}' not defined for position '{position}'")

    # Generate stats based on the skill level
    stats = {stat: random.randint(rng[0], rng[1]) for stat, rng in STAT_RANGES[position][skillLvl].items()}

    # ------------------ Correlated Stats ------------------

    # Physicals affecting finishing
    if stats["vertical"] > 85:
        stats["driving_dunk"] = max(stats["driving_dunk"], stats["vertical"] - 10)
        stats["standing_dunk"] = max(stats["standing_dunk"], stats["vertical"] - 15)

    # Finishing correlations
    if stats["driving_layup"] > 85 or stats["driving_dunk"] > 85:
        stats["close_shot"] = max(stats["close_shot"], max(stats["driving_layup"], stats["driving_dunk"]) - 5)
    if stats["post_moves"] > 85:
        stats["close_shot"] = max(stats["close_shot"], stats["post_moves"] - 5)

    # Shooting correlations
    if stats["mid_range_shot"] > 85:
        stats["free_throw"] = max(stats["free_throw"], stats["mid_range_shot"] - 5)
    if stats["three_point_shot"] > 85:
        stats["free_throw"] = max(stats["free_throw"], stats["three_point_shot"] - 10)

    # Playmaking correlations
    if stats["pass_accuracy"] > 85:
        stats["ball_handle"] = max(stats["ball_handle"], stats["pass_accuracy"] - 10)
    if stats["speed_with_ball"] > 85:
        stats["speed"] = max(stats["speed"], stats["speed_with_ball"] - 5)
        stats["pass_accuracy"] = max(stats["pass_accuracy"], stats["speed_with_ball"] - 10)

    # Defense correlations
    if stats["perimeter_defense"] > 85:
        stats["steal"] = max(stats["steal"], stats["perimeter_defense"] - 10)
    if stats["interior_defense"] > 85:
        stats["block"] = max(stats["block"], stats["interior_defense"] - 10)

    # Rebounding correlations
    if stats["strength"] > 80:
        stats["offensive_rebounding"] = max(stats["offensive_rebounding"], stats["strength"] - 10)
        stats["defensive_rebounding"] = max(stats["defensive_rebounding"], stats["strength"] - 5)
    if stats["offensive_rebounding"] > 80 or stats["defensive_rebounding"] > 80:
        stats["strength"] = max(stats["strength"], stats["offensive_rebounding"] - 10)

    # Speed correlations
    if stats["speed"] > 85:
        stats["speed_with_ball"] = max(stats["speed_with_ball"], stats["speed"] - 5)

    # ------------------ Overall, Height & Weight ------------------
    # Define weights for each stat
    weights = {
        "close_shot": 1.0,
        "driving_layup": 1.0,
        "driving_dunk": 0.8,
        "standing_dunk": 0.8,
        "post_moves": 0.7,
        "mid_range_shot": 1.0,
        "three_point_shot": 1.0,
        "free_throw": 0.4,
        "pass_accuracy": 1.0,
        "ball_handle": 1.0,
        "speed_with_ball": 0.6,
        "interior_defense": 0.6,
        "perimeter_defense": 0.6,
        "steal": 1.0,
        "block": 0.8,
        "offensive_rebounding": 0.6,
        "defensive_rebounding": 0.7,
        "speed": 0.4,
        "strength": 0.4,
        "vertical": 0.4,
        "potential": 0.0,
    }

    overall = int(sum(stats[k] * weights.get(k, 1) for k in stats) / sum(weights.values()))

    height = random.randint(*HEIGHT_RANGES[position])
    weight = random.randint(*WEIGHT_RANGES[position])

    # ------------------ Specialization (Top 3 skill stats) ------------------
    excluded_fields = {"speed", "strength", "vertical", "potential"}
    skill_stats = {k: v for k, v in stats.items() if k not in excluded_fields}
    sorted_stats = sorted(skill_stats.items(), key=lambda x: x[1], reverse=True)
    top_three = [stat for stat, value in sorted_stats[:3]]
    player_state = random.choice(US_STATES)

    return {
        "name": f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}",
        "position": position,
        "overall": overall,
        "height": height,
        "weight": weight,
        "specialization": top_three,
        "state": player_state,
        **stats,
    }

