# Generated by Django 5.2.6 on 2025-09-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=2)),
                ('overall', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('specialization', models.JSONField(default=list)),
                ('close_shot', models.IntegerField()),
                ('driving_layup', models.IntegerField()),
                ('driving_dunk', models.IntegerField()),
                ('standing_dunk', models.IntegerField()),
                ('post_moves', models.IntegerField()),
                ('mid_range_shot', models.IntegerField()),
                ('three_point_shot', models.IntegerField()),
                ('free_throw', models.IntegerField()),
                ('pass_accuracy', models.IntegerField()),
                ('ball_handle', models.IntegerField()),
                ('speed_with_ball', models.IntegerField()),
                ('interior_defense', models.IntegerField()),
                ('perimeter_defense', models.IntegerField()),
                ('steal', models.IntegerField()),
                ('block', models.IntegerField()),
                ('offensive_rebounding', models.IntegerField()),
                ('defensive_rebounding', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('vertical', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('recruiting_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.recruitingclass')),
            ],
        ),
    ]
