# Generated by Django 5.2.6 on 2025-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
