# Generated by Django 5.2.6 on 2025-09-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
